### ISSUE TITLE
Invalid credentials error not surfaced to user

### ISSUE THREAD

**Issue by craiga** [mvlnetdev/photoprism_client#13]
When attempting to use an invalid set of credentials, the user sees this error:

```python
Traceback (most recent call last):
  …
  File "…/my_cool_code.py", line 22, in main
    session.create()
  File "…site-packages/photoprism/Session.py", line 88, in create
    self.session_id = data["id"]
                      ~~~~^^^^^^
KeyError: 'id'
```

It should throw some kind of authentication failed exception.

**Comment by craiga** [comment]
It looks like `data` contains `{'error': 'Invalid credentials'}` here.

This should be a relatively simple fix I might have a go at myself, but I'm documenting it here just in case I run out of enthusiasm for it.
